<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::all();

        $products = [
            // Analgesik & Antipiretik
            [
                'category_name' => 'Analgesik & Antipiretik',
                'name' => 'Paramex Paracetamol 500mg',
                'unit' => 'tablet',
                'purchase_price' => 150,
                'selling_price' => 250,
                'stock' => 500,
                'is_active' => true,
                'expiry_date' => '2027-05-20',
            ],
            [
                'category_name' => 'Analgesik & Antipiretik',
                'name' => 'Panadol Extra 500mg',
                'unit' => 'tablet',
                'purchase_price' => 200,
                'selling_price' => 350,
                'stock' => 300,
                'is_active' => true,
                'expiry_date' => '2026-12-15',
            ],
            [
                'category_name' => 'Analgesik & Antipiretik',
                'name' => 'Bodrex Migra',
                'unit' => 'tablet',
                'purchase_price' => 180,
                'selling_price' => 300,
                'stock' => 250,
                'is_active' => true,
                'expiry_date' => '2026-10-10',
            ],
            [
                'category_name' => 'Analgesik & Antipiretik',
                'name' => 'Biogesic Paracetamol 500mg',
                'unit' => 'tablet',
                'purchase_price' => 140,
                'selling_price' => 230,
                'stock' => 600,
                'is_active' => true,
                'expiry_date' => '2027-08-25',
            ],
            [
                'category_name' => 'Analgesik & Antipiretik',
                'name' => 'Osfalgin',
                'unit' => 'tablet',
                'purchase_price' => 250,
                'selling_price' => 450,
                'stock' => 150,
                'is_active' => true,
                'expiry_date' => '2026-09-30',
            ],
            [
                'category_name' => 'Analgesik & Antipiretik',
                'name' => 'Saridon',
                'unit' => 'tablet',
                'purchase_price' => 220,
                'selling_price' => 380,
                'stock' => 200,
                'is_active' => true,
                'expiry_date' => '2026-11-12',
            ],

            // Antibiotik
            [
                'category_name' => 'Antibiotik',
                'name' => 'Amoxicillin 500mg (Amoxan)',
                'unit' => 'kapsul',
                'purchase_price' => 180,
                'selling_price' => 320,
                'stock' => 200,
                'is_active' => true,
                'expiry_date' => '2026-06-15',
            ],
            [
                'category_name' => 'Antibiotik',
                'name' => 'Ciprofloxacin 500mg (Ciprobay)',
                'unit' => 'tablet',
                'purchase_price' => 350,
                'selling_price' => 550,
                'stock' => 120,
                'is_active' => true,
                'expiry_date' => '2026-08-20',
            ],
            [
                'category_name' => 'Antibiotik',
                'name' => 'Erythromycin 250mg',
                'unit' => 'tablet',
                'purchase_price' => 120,
                'selling_price' => 220,
                'stock' => 180,
                'is_active' => true,
                'expiry_date' => '2026-07-10',
            ],
            [
                'category_name' => 'Antibiotik',
                'name' => 'Doxycycline 100mg',
                'unit' => 'kapsul',
                'purchase_price' => 180,
                'selling_price' => 320,
                'stock' => 150,
                'is_active' => true,
                'expiry_date' => '2026-09-05',
            ],
            [
                'category_name' => 'Antibiotik',
                'name' => 'Augmentin 500mg',
                'unit' => 'tablet',
                'purchase_price' => 1200,
                'selling_price' => 1800,
                'stock' => 80,
                'is_active' => true,
                'expiry_date' => '2026-05-15',
            ],
            [
                'category_name' => 'Antibiotik',
                'name' => 'Zithromax Azithromycin 500mg',
                'unit' => 'tablet',
                'purchase_price' => 450,
                'selling_price' => 750,
                'stock' => 100,
                'is_active' => true,
                'expiry_date' => '2026-10-30',
            ],

            // Antivirus
            [
                'category_name' => 'Antivirus',
                'name' => 'Acyclovir 400mg',
                'unit' => 'tablet',
                'purchase_price' => 250,
                'selling_price' => 400,
                'stock' => 100,
                'is_active' => true,
                'expiry_date' => '2027-01-20',
            ],
            [
                'category_name' => 'Antivirus',
                'name' => 'Oseltamivir 75mg (Tamiflu)',
                'unit' => 'kapsul',
                'purchase_price' => 850,
                'selling_price' => 1350,
                'stock' => 50,
                'is_active' => true,
                'expiry_date' => '2026-12-01',
            ],

            // Obat Batuk & Pilek
            [
                'category_name' => 'Obat Batuk & Pilek',
                'name' => 'Decolsin Tekstur Lechat',
                'unit' => 'botol',
                'purchase_price' => 12000,
                'selling_price' => 18000,
                'stock' => 30,
                'is_active' => true,
                'expiry_date' => '2027-03-15',
            ],
            [
                'category_name' => 'Obat Batuk & Pilek',
                'name' => 'Siladex Cough Medicine',
                'unit' => 'botol',
                'purchase_price' => 10000,
                'selling_price' => 15500,
                'stock' => 45,
                'is_active' => true,
                'expiry_date' => '2027-02-28',
            ],
            [
                'category_name' => 'Obat Batuk & Pilek',
                'name' => 'Bisolvon Tablet',
                'unit' => 'tablet',
                'purchase_price' => 180,
                'selling_price' => 280,
                'stock' => 300,
                'is_active' => true,
                'expiry_date' => '2027-06-10',
            ],
            [
                'category_name' => 'Obat Batuk & Pilek',
                'name' => 'Woods Antigrip',
                'unit' => 'botol',
                'purchase_price' => 15000,
                'selling_price' => 22500,
                'stock' => 25,
                'is_active' => true,
                'expiry_date' => '2026-11-20',
            ],
            [
                'category_name' => 'Obat Batuk & Pilek',
                'name' => 'Actived Cold & Flu',
                'unit' => 'tablet',
                'purchase_price' => 220,
                'selling_price' => 380,
                'stock' => 250,
                'is_active' => true,
                'expiry_date' => '2027-01-05',
            ],
            [
                'category_name' => 'Obat Batuk & Pilek',
                'name' => 'Vicks 45',
                'unit' => 'tablet',
                'purchase_price' => 200,
                'selling_price' => 350,
                'stock' => 280,
                'is_active' => true,
                'expiry_date' => '2026-12-30',
            ],

            // Obat Diabetes
            [
                'category_name' => 'Obat Diabetes',
                'name' => 'Metformin 500mg',
                'unit' => 'tablet',
                'purchase_price' => 180,
                'selling_price' => 280,
                'stock' => 400,
                'is_active' => true,
                'expiry_date' => '2027-08-10',
            ],
            [
                'category_name' => 'Obat Diabetes',
                'name' => 'Glucophage 500mg',
                'unit' => 'tablet',
                'purchase_price' => 350,
                'selling_price' => 550,
                'stock' => 200,
                'is_active' => true,
                'expiry_date' => '2027-09-15',
            ],
            [
                'category_name' => 'Obat Diabetes',
                'name' => 'Glibenclamide 5mg',
                'unit' => 'tablet',
                'purchase_price' => 120,
                'selling_price' => 200,
                'stock' => 350,
                'is_active' => true,
                'expiry_date' => '2027-04-20',
            ],
            [
                'category_name' => 'Obat Diabetes',
                'name' => 'Sucralfat Antasida',
                'unit' => 'tablet',
                'purchase_price' => 250,
                'selling_price' => 400,
                'stock' => 180,
                'is_active' => true,
                'expiry_date' => '2026-10-15',
            ],

            // Obat Hipertensi
            [
                'category_name' => 'Obat Hipertensi',
                'name' => 'Captopril 25mg',
                'unit' => 'tablet',
                'purchase_price' => 100,
                'selling_price' => 180,
                'stock' => 450,
                'is_active' => true,
                'expiry_date' => '2027-11-12',
            ],
            [
                'category_name' => 'Obat Hipertensi',
                'name' => 'Amlodipine 5mg (Amlopidin)',
                'unit' => 'tablet',
                'purchase_price' => 180,
                'selling_price' => 300,
                'stock' => 300,
                'is_active' => true,
                'expiry_date' => '2027-12-05',
            ],
            [
                'category_name' => 'Obat Hipertensi',
                'name' => 'Losartan 50mg',
                'unit' => 'tablet',
                'purchase_price' => 250,
                'selling_price' => 420,
                'stock' => 220,
                'is_active' => true,
                'expiry_date' => '2027-05-30',
            ],
            [
                'category_name' => 'Obat Hipertensi',
                'name' => 'Calmartin 5mg',
                'unit' => 'tablet',
                'purchase_price' => 180,
                'selling_price' => 300,
                'stock' => 200,
                'is_active' => true,
                'expiry_date' => '2026-08-10',
            ],
            [
                'category_name' => 'Obat Hipertensi',
                'name' => 'Concor 5mg',
                'unit' => 'tablet',
                'purchase_price' => 350,
                'selling_price' => 550,
                'stock' => 150,
                'is_active' => true,
                'expiry_date' => '2026-09-25',
            ],

            // Suplemen & Vitamin
            [
                'category_name' => 'Suplemen & Vitamin',
                'name' => 'Vitamin C 500mg (Ascoril C)',
                'unit' => 'tablet',
                'purchase_price' => 120,
                'selling_price' => 220,
                'stock' => 500,
                'is_active' => true,
                'expiry_date' => '2027-10-15',
            ],
            [
                'category_name' => 'Suplemen & Vitamin',
                'name' => 'Blackmores Vitamin C 500mg',
                'unit' => 'tablet',
                'purchase_price' => 350,
                'selling_price' => 600,
                'stock' => 200,
                'is_active' => true,
                'expiry_date' => '2026-12-20',
            ],
            [
                'category_name' => 'Suplemen & Vitamin',
                'name' => 'Enervon C',
                'unit' => 'tablet',
                'purchase_price' => 200,
                'selling_price' => 350,
                'stock' => 350,
                'is_active' => true,
                'expiry_date' => '2027-02-10',
            ],
            [
                'category_name' => 'Suplemen & Vitamin',
                'name' => 'Sedamen (Vitamin B1, B6, B12)',
                'unit' => 'tablet',
                'purchase_price' => 180,
                'selling_price' => 300,
                'stock' => 300,
                'is_active' => true,
                'expiry_date' => '2027-04-15',
            ],
            [
                'category_name' => 'Suplemen & Vitamin',
                'name' => 'Hemaviton',
                'unit' => 'tablet',
                'purchase_price' => 200,
                'selling_price' => 350,
                'stock' => 280,
                'is_active' => true,
                'expiry_date' => '2026-11-30',
            ],
            [
                'category_name' => 'Suplemen & Vitamin',
                'name' => 'Blood Nutrition (premalin)',
                'unit' => 'tablet',
                'purchase_price' => 180,
                'selling_price' => 320,
                'stock' => 220,
                'is_active' => true,
                'expiry_date' => '2027-06-25',
            ],
            [
                'category_name' => 'Suplemen & Vitamin',
                'name' => 'Imunofor (Vitamin & Zinc)',
                'unit' => 'tablet',
                'purchase_price' => 250,
                'selling_price' => 420,
                'stock' => 200,
                'is_active' => true,
                'expiry_date' => '2027-01-20',
            ],

            // Obat Lambung & Antacida
            [
                'category_name' => 'Obat Lambung & Antacida',
                'name' => 'Polysilane Plus',
                'unit' => 'tablet',
                'purchase_price' => 220,
                'selling_price' => 380,
                'stock' => 250,
                'is_active' => true,
                'expiry_date' => '2027-05-15',
            ],
            [
                'category_name' => 'Obat Lambung & Antacida',
                'name' => 'Mylanta Antasida',
                'unit' => 'botol',
                'purchase_price' => 18000,
                'selling_price' => 26500,
                'stock' => 40,
                'is_active' => true,
                'expiry_date' => '2026-08-30',
            ],
            [
                'category_name' => 'Obat Lambung & Antacida',
                'name' => 'Gastrogantin',
                'unit' => 'tablet',
                'purchase_price' => 350,
                'selling_price' => 580,
                'stock' => 120,
                'is_active' => true,
                'expiry_date' => '2026-10-10',
            ],
            [
                'category_name' => 'Obat Lambung & Antacida',
                'name' => 'Pantoprazole 20mg',
                'unit' => 'kapsul',
                'purchase_price' => 400,
                'selling_price' => 680,
                'stock' => 100,
                'is_active' => true,
                'expiry_date' => '2027-03-20',
            ],
            [
                'category_name' => 'Obat Lambung & Antacida',
                'name' => 'Proton-M (Omeprazole)',
                'unit' => 'kapsul',
                'purchase_price' => 380,
                'selling_price' => 620,
                'stock' => 90,
                'is_active' => true,
                'expiry_date' => '2027-01-15',
            ],
            [
                'category_name' => 'Obat Lambung & Antacida',
                'name' => 'Loperamide (Lomodian) 2mg',
                'unit' => 'tablet',
                'purchase_price' => 150,
                'selling_price' => 250,
                'stock' => 300,
                'is_active' => true,
                'expiry_date' => '2027-04-10',
            ],

            // Obat Kulit & Kelamin
            [
                'category_name' => 'Obat Kulit & Kelamin',
                'name' => 'Cortison 1% 5g',
                'unit' => 'tube',
                'purchase_price' => 8500,
                'selling_price' => 12500,
                'stock' => 50,
                'is_active' => true,
                'expiry_date' => '2027-11-20',
            ],
            [
                'category_name' => 'Obat Kulit & Kelamin',
                'name' => 'Elocom 5g',
                'unit' => 'tube',
                'purchase_price' => 12000,
                'selling_price' => 18000,
                'stock' => 40,
                'is_active' => true,
                'expiry_date' => '2027-12-15',
            ],
            [
                'category_name' => 'Obat Kulit & Kelamin',
                'name' => 'Nystatin cream',
                'unit' => 'tube',
                'purchase_price' => 7000,
                'selling_price' => 11000,
                'stock' => 60,
                'is_active' => true,
                'expiry_date' => '2026-09-05',
            ],
            [
                'category_name' => 'Obat Kulit & Kelamin',
                'name' => 'Remacyl Cream 25g',
                'unit' => 'tube',
                'purchase_price' => 15000,
                'selling_price' => 22500,
                'stock' => 35,
                'is_active' => true,
                'expiry_date' => '2027-02-10',
            ],
            [
                'category_name' => 'Obat Kulit & Kelamin',
                'name' => 'Ketokonazole 2% (Nizoral)',
                'unit' => 'tablet',
                'purchase_price' => 280,
                'selling_price' => 480,
                'stock' => 150,
                'is_active' => true,
                'expiry_date' => '2026-12-30',
            ],

            // Obat Mata
            [
                'category_name' => 'Obat Mata',
                'name' => 'Cendo Mucomyst 0.5% eye drops',
                'unit' => 'botol',
                'purchase_price' => 12000,
                'selling_price' => 18000,
                'stock' => 25,
                'is_active' => true,
                'expiry_date' => '2027-06-20',
            ],
            [
                'category_name' => 'Obat Mata',
                'name' => 'Cendo Xitrol',
                'unit' => 'botol',
                'purchase_price' => 15000,
                'selling_price' => 22500,
                'stock' => 30,
                'is_active' => true,
                'expiry_date' => '2027-08-15',
            ],
            [
                'category_name' => 'Obat Mata',
                'name' => 'Vigamox 5ml',
                'unit' => 'botol',
                'purchase_price' => 45000,
                'selling_price' => 68000,
                'stock' => 15,
                'is_active' => true,
                'expiry_date' => '2027-01-30',
            ],
            [
                'category_name' => 'Obat Mata',
                'name' => 'Cendo C eye drops',
                'unit' => 'botol',
                'purchase_price' => 8000,
                'selling_price' => 12500,
                'stock' => 40,
                'is_active' => true,
                'expiry_date' => '2026-11-10',
            ],
            [
                'category_name' => 'Obat Mata',
                'name' => 'Meycin Eye Ointment',
                'unit' => 'tube',
                'purchase_price' => 10000,
                'selling_price' => 15500,
                'stock' => 45,
                'is_active' => true,
                'expiry_date' => '2027-03-05',
            ],
        ];

        foreach ($products as $productData) {
            $category = $categories->firstWhere('name', $productData['category_name']);
            if ($category) {
                Product::create([
                    'category_id' => $category->id,
                    'name' => $productData['name'],
                    'unit' => $productData['unit'],
                    'purchase_price' => $productData['purchase_price'],
                    'selling_price' => $productData['selling_price'],
                    'stock' => $productData['stock'],
                    'is_active' => $productData['is_active'],
                    'expiry_date' => $productData['expiry_date'],
                ]);
            }
        }
    }
}
